spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint:  oss-us-east-1.aliyuncs.com
      secret-key: 7AHMdejiZ5MrAVxKESpICU3RJ3uxxQ
      access-key: LTAI5tAvFpxC7YxWbcqwKuuD
      bucket: gulimall-youdong
  application:
    name: gulimall-third-party

server:
  port: 30000

